// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMHIEDAKYS8_Nw2nW9fcTsVLenZt8B_V8',
    appId: '1:587126562561:web:6214540afd385e05ab0500',
    messagingSenderId: '587126562561',
    projectId: 'flutter-app-sergio',
    authDomain: 'flutter-app-sergio.firebaseapp.com',
    storageBucket: 'flutter-app-sergio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZDr-C1GsKlSGoz-vdqDC7YqH1wYjVDb4',
    appId: '1:587126562561:android:ca25ee0f773515cfab0500',
    messagingSenderId: '587126562561',
    projectId: 'flutter-app-sergio',
    storageBucket: 'flutter-app-sergio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHgz-SPzZy5HDCAK3JKwF3mXRnBnzK5co',
    appId: '1:587126562561:ios:bbb4268fd339f47fab0500',
    messagingSenderId: '587126562561',
    projectId: 'flutter-app-sergio',
    storageBucket: 'flutter-app-sergio.appspot.com',
    iosClientId: '587126562561-upmd7132dq7iortlil78h0nie3ph5p9m.apps.googleusercontent.com',
    iosBundleId: 'com.sergio.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHgz-SPzZy5HDCAK3JKwF3mXRnBnzK5co',
    appId: '1:587126562561:ios:bbb4268fd339f47fab0500',
    messagingSenderId: '587126562561',
    projectId: 'flutter-app-sergio',
    storageBucket: 'flutter-app-sergio.appspot.com',
    iosClientId: '587126562561-upmd7132dq7iortlil78h0nie3ph5p9m.apps.googleusercontent.com',
    iosBundleId: 'com.sergio.flutterapp',
  );
}
